### ISSUE TITLE
 php-dom not installed.

### ISSUE THREAD

**Issue by torounit** [Launch-with-1-Click/lw1-amimoto#122]
https://make.wordpress.org/hosting/handbook/handbook/server-environment/#php-extensions

WordPress recommends installing `php-dom` extension.

**Comment by wokamoto** [comment]
php-dom は、デフォルトでインストール( https://github.com/Launch-with-1-Click/lw1-amimoto/blob/2016.01/attributes/03_php.rb#L65 )している php-xml エクステンションに含まれています。
デフォルト状態の AMIMOTO AMI では DOMDocument クラスが使用可能となっています。

```
$ php -r 'var_dump(class_exists("DOMDocument"));'
bool(true)
```
